### ISSUE TITLE
Console and Windows

### ISSUE THREAD

**Issue by camael24** [hoaproject/Console#35]
Hi guy :-D

I am here to explain my problem to use Hoa\Console on windows, i have two Console emulator, cmd.exe and [cmder.exe](http://bliker.github.io/cmder/).

I run same script on both.

Cmd
======
I have this output https://dl.dropboxusercontent.com/u/32185828/Sans%20titre-3.jpg

**Comment by jubianchi** [comment]
duplicate of #36?

**Comment by camael24** [comment]
Yes its true, my bad 

Envoyé de mon iPad
