### ISSUE TITLE
Namespace conflit with library not yet updated

### ISSUE THREAD

**Issue by Pierozi** [hoaproject/Console#38]
The recent change on commit add3edbef for remove `from_import` have break `Bin` of library still continue to use namespace declaration with bracketed.

```bash
$ hoa worker:start -h
PHP Fatal error:  Cannot mix bracketed namespace declarations with unbracketed namespace declarations in /usr/local/lib/Hoa.central/Hoa/Console/Dispatcher/Kit.php on line 37
```

A few library are impacted : 

 - Hoa\HTTP
 - Hoa\Praspel
 - Hoa\Realdom
 - Hoa\Worker
 - Hoa\Xml

**Comment by Hywan** [comment]
This is a bug in PHP, not in Hoa. But yes, we have to drop PHP5.3 on all libraries to fix it.
