### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by dantleech** [hoaproject/Console#64]
Are there any plans in to include a table renderer in this library? The [Symfony](https://github.com/symfony/console) one is good for most use cases, but is limited if you want to do anything advanced. For example, the following features would be useful:

- Colspan.
- Border formatting (on cells, rows, columns or the table).
- Padding.
- Specify widths in percentages (on cells, columns, or the table).
- Auto wrap text OR truncate text depending on cell size.

**Comment by Hywan** [comment]
@dantleech You have `Hoa\Console\Chrome\Text` but we don't know if we are going to remove it or not.

**Comment by Hywan** [comment]
Can we close this issue?

**Comment by dantleech** [comment]
Sure
