### ISSUE TITLE
Autocompletion forgets counting extra spaces

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Console#67]
The autocompletion is OK while I'm typing a word. My word is completed, then I continue at the end. 
I always add a space if my command has some words. 

But if I typed a first word and the following space (or more) then I type "tab": my extra space is remove. 
If I type again on "tab" the first letter of the previous word will be duplicate. 

I guess LineLength is not updated when the autocompleter remove the ending space chars. 
Moreover I would like one extra space after the autocompleted word ;)

**Comment by Hywan** [comment]
Hello,

Can you please give us a detailed scenario, line by line, please? Something like:
```
$ hello<space>
$ hello<space><tab>
$ helloo
```
Thanks!

**Comment by 1e1** [comment]
```php
$rl = new Hoa\Console\Readline\Readline();
$rl->setAutocompleter(new Hoa\Console\Readline\Autocompleter\Word([
    'help',
    'clear',
    'quit',
]));

do {
    $line = $rl->readLine('> ');
    // --- 
            echo '< ', $line;
    // ---

    echo PHP_EOL, PHP_EOL;
} while (false !== $line && 'quit' !== $line);
```

The shortest way:
$ quit<space><tab>
$ qquit

**Comment by Hywan** [comment]
Indeeed, this is a bug. I will try to fix it.

**Comment by Hywan** [comment]
@1e1 Can you test the patch in #68 please?

**Comment by 1e1** [comment]
Thx, it works!

**Comment by Hywan** [comment]
@vonglasow seems to have some issue with #68. Let's wait on him.

**Comment by vonglasow** [comment]
It was due to run all tests with xdebug but without this library everything is good.
