### ISSUE TITLE
unset Autocompleter

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Console#69]
We can't unset an autocompleter. 

If I do `$rl->setAutocompleter(null);`, I obtain: 
```
Fatal error: Uncaught TypeError: Argument 1 passed to Hoa\Console\Readline\Readline::setAutocompleter() must implement interface Hoa\Console\Readline\Autocompleter\Autocompleter, null given
```

Can you add the `unsetAutocompleter()` method?

**Comment by Hywan** [comment]
Yup, you cannot.

**Comment by Hywan** [comment]
You can use the aggregate autocompleter, namely `Hoa\Console\Readline\Autocompleter\Aggregate`. It wraps the collection of autocompleters inside an `ArrayObject`. With the `getAutocompleters` method, you can set add or remove autocompleters on-the-fly.
